"""add_medicine_and_prescription

Revision ID: 807ac94db43d
Revises: ecd6255b15b4
Create Date: 2026-09-06 15:01:15.248906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '807ac94db43d'
down_revision: Union[str, Sequence[str], None] = 'ecd6255b15b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('generic_name', sa.String(length=200), nullable=True),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generic_name', 'strength', 'dosage_form', name='uq_medicine_identify')
    )
    op.create_index(op.f('ix_medicines_id'), 'medicines', ['id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=True),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('medicine_strength', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('total_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('morning_dose', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('noon_dose', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('evening_dose', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('night_dose', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('prn_condition', sa.Text(), nullable=True),
    sa.CheckConstraint('morning_dose >= 0 AND noon_dose >= 0 AND evening_dose >= 0 AND night_dose >= 0', name='ck_item_doses_positive'),
    sa.CheckConstraint('total_quantity >= 0', name='ck_item_quatity_positive'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_items_id'), 'prescription_items', ['id'], unique=False)
    op.create_index(op.f('ix_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False)
    op.add_column('prescriptions', sa.Column('prescribed_by_user_id', sa.Integer(), nullable=True))
    op.add_column('prescriptions', sa.Column('diagnosis', sa.Text(), nullable=True))
    op.add_column('prescriptions', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('prescriptions', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('prescriptions', sa.Column('status', sa.String(length=20), server_default=sa.text("'draft'"), nullable=False))
    op.add_column('prescriptions', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('prescriptions', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('prescriptions', 'elder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_prescriptions_elder_id'), 'prescriptions', ['elder_id'], unique=False)
    op.create_foreign_key(
        'fk_prescriptions_prescribed_by_user_id_users',
        'prescriptions',
        'users',
        ['prescribed_by_user_id'],
        ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_prescriptions_prescribed_by_user_id_users', 'prescriptions', type_='foreignkey')
    op.drop_index(op.f('ix_prescriptions_elder_id'), table_name='prescriptions')
    op.alter_column('prescriptions', 'elder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('prescriptions', 'updated_at')
    op.drop_column('prescriptions', 'created_at')
    op.drop_column('prescriptions', 'status')
    op.drop_column('prescriptions', 'end_date')
    op.drop_column('prescriptions', 'note')
    op.drop_column('prescriptions', 'diagnosis')
    op.drop_column('prescriptions', 'prescribed_by_user_id')
    op.drop_index(op.f('ix_prescription_items_prescription_id'), table_name='prescription_items')
    op.drop_index(op.f('ix_prescription_items_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_medicines_id'), table_name='medicines')
    op.drop_table('medicines')
    # ### end Alembic commands ###
